### ISSUE TITLE
[Bug]: Translation functionality of Titles of Filters is missing

### ISSUE THREAD

**Issue by vaggelisk** [vuestorefront/storefront-nuxt2-magento2#6]
### Describe the Bug

At Category Page at Filters left sidebar, translations functionality are missing.

![image](https://user-images.githubusercontent.com/18349081/223169033-bbd799f7-a4e4-40bd-89d8-b74893ba96b6.png)

### Current behavior

Even if I am in german language edition, and there are the translations of these words (_Bath_, _Kitchen_, _Magazine_), the titles display in english.

### Expected behavior

To display the titles in german.

### Steps to reproduce

Open the VSF, go to Category Page, see the Filters.

### What version of Vue Storefront are you using?

2.x

### What version of Node.js are you using?

16.x.x

### What browser (and version) are you using?

firefox, chrome

### What operating system (and version) are you using?

not relevant

### Able to fix / change the documentation?

- [X] Yes
- [ ] No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bartoszherba** [comment]
@vaggelisk Hello!
This is the wrong approach. Labels of attributes should be not translated on the front because they should come already been translated from the M2 backend.

**Comment by vaggelisk** [comment]
It's true. I checked it as well in the M2 AdminPanel, System -> Attributes -> Edit [specific] Attribute -> Manage Labels of each language.  

@rohrig should i close the issue?

**Comment by rohrig** [comment]
@vaggelisk I think it makes sense to close this. Thanks for clarifying @bartoszherba
